# Gerando Números Aleatórios com NumPy

In [1]:
import numpy as np

### Gerando um número aleatório da distribuição normal

In [5]:
np.random.normal()

1.3166447059864363

### Gerando quatro números aleatórios da distribuição normal

In [3]:
np.random.normal(size=4)

array([ 1.68673837,  0.23211421,  0.97353059, -0.54626391])

### Gerando cinco números aleatórios da distribuição uniforme

In [8]:
np.random.uniform(size=5)

array([0.87636279, 0.8907913 , 0.56209048, 0.24741483, 0.12486639])

### Gerando dez números inteiros aleatórios entre 1 e 100

In [7]:
np.random.randint(low=1, high=100, size=10)

array([14, 43, 12, 40, 29, 13, 54, 58, 53,  7])