# Gerando Números Aleatórios com NumPy

#### Iniciamos importando a biblioteca **NumPy** como **np**:

In [1]:
import numpy as np

#### Gerando um número aleatório da distribuição normal:

In [2]:
np.random.normal()

0.715579108218062

Podemos ainda, oferecer a essa função três argumentos, respectivamente:
    
- **loc:** Média ("centro") da distribuição.
- **scale:** Desvio padrão (dispersão ou "largura") da distribuição. Deve ser um número não negativo.
- **size:** Um número inteiro que representará o tamanho do array.

In [3]:
np.random.normal(3, 1.5, 10)

array([0.42723943, 0.37945088, 4.30156074, 3.38213508, 4.21666633,
       3.07530908, 2.57894109, 2.38034756, 3.25254361, 2.92784972])

#### Gerando quatro números aleatórios da distribuição normal:

In [4]:
np.random.normal(size=4)

array([ 0.85840722, -0.21178012,  0.02242227,  1.44939624])

#### Gerando cinco números aleatórios da distribuição uniforme:

In [5]:
np.random.uniform(size=5)

array([2.57201027e-04, 1.75296648e-01, 6.51284258e-01, 1.85664349e-01,
       7.01087163e-01])

#### Gerando dez números inteiros aleatórios entre 1 e 100:

In [6]:
np.random.randint(low=1, high=100, size=10)

array([11, 35, 26, 88, 34, 67, 68, 82, 27, 65])

#### Gere uma amostra aleatória uniforme de um array de itens, de tamanho 10:

In [7]:
np.random.choice(['cara','coroa'], 10)

array(['cara', 'cara', 'coroa', 'coroa', 'coroa', 'coroa', 'cara',
       'coroa', 'coroa', 'coroa'], dtype='<U5')